// PaymentFormGen.cs
// This file is typically generated by a tool (e.g., UI designer)
// You should NOT manually edit this file

partial class PaymentForm
{
    public decimal Amount;

    public void ProcessPayment()
    {
        // Call a partial method as a customization hook
        ValidatePayment(Amount);

        Console.WriteLine("Processing payment...");
    }

    // Partial method definition (no implementation here)
    partial void ValidatePayment(decimal amount);
}
